Repository drimov/CookRecipes, pull requests merged in 2023-09, with the labels that each got.

#5 Configuration projet
  .eslintrc.cjs
  .prettierignore
  .prettierrc.cjs
  components.json
  package.json
  pnpm-lock.yaml
  postcss.config.js
  src/App.css
  src/App.tsx
  src/components/ui/avatar.tsx
  src/components/ui/button-styles.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/form.tsx
  src/components/ui/hover-card.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/navigation-menu-styles.tsx
  src/components/ui/navigation-menu.tsx
  src/components/ui/select.tsx
  src/components/ui/skeleton.tsx
  src/components/ui/switch.tsx
  src/components/ui/tabs.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/components/ui/toggle-variant.tsx
  src/components/ui/toggle.tsx
  src/components/ui/use-toast.ts
  src/lib/utils.ts
  src/main.tsx
  tailwind.config.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement

#9 feat: ✨Ajout + mise en place de supabase database
  .env
  package.json
  pnpm-lock.yaml
  src/commons/constants.ts
  src/env.d.ts
  tsconfig.json
Labels: enhancement

#10 Mise en place du theme
  src/App.tsx
  src/components/mode-toggle.tsx
  src/context/ThemeContext.tsx
  src/hooks/useTheme.ts
  src/pages/Home.tsx
Labels: enhancement

#14 Mise-en-place-de-react-query
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/main.tsx
Labels: enhancement

#15 Warning eslint fast refresh
  src/components/ui/form/index.tsx
  src/hooks/useFormField.tsx
Labels: bug

#17 Fix-configuration-shadcn-ui
  components.json
Labels: bug

#19 Standardisation composants un fichier/dossier par composant
  src/components/ui/button/index.tsx
  src/components/ui/button/variants.tsx
  src/components/ui/form.tsx
  src/components/ui/navigation-menu/index.tsx
  src/components/ui/navigation-menu/styles.tsx
  src/components/ui/toggle/index.tsx
  src/components/ui/toggle/variants.tsx
Labels: enhancement

#24 Wrong import for shadcn-ui
  src/components/ui/button/index.tsx
  src/components/ui/navigation-menu/index.tsx
  src/components/ui/toggle/index.tsx
Labels: bug

#28 Mise en place des tests
  cypress.config.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package.json
  pnpm-lock.yaml
  src/setup.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement

#25 2 Mise en place de React Router
  src/App.tsx
  src/pages/Authentification.tsx
  src/pages/Home.tsx
  src/pages/Produit.tsx
  src/pages/Profil.tsx
  src/pages/Search.tsx
  src/pages/index.ts
Labels: help wanted

#34 Prettier tailwindcss
  .prettierrc.cjs
  package.json
  pnpm-lock.yaml
  src/pages/Home.tsx
Labels: enhancement

#37 Correction eslint prettier
  .eslintrc.cjs
  .prettierignore
  cypress.config.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package.json
  pnpm-lock.yaml
  src/App.css
  src/pages/Produit.tsx
  src/pages/Profil.tsx
  src/pages/Search.tsx
  tsconfig.json
  vite.config.ts
Labels: bug

#39 Configuration pre commit hook
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
Labels: enhancement

#43 desactivation-regle-eslint
  .eslintrc.cjs
Labels: bug

#46 refactor: 🎨suppression de fichier non utilisé
  public/vite.svg
  src/assets/react.svg
  src/index.css
  src/main.tsx
Labels: enhancement

#48 Composant link
  src/components/ui/link.tsx
  src/pages/Home.tsx
  src/types/app.ts
Labels: enhancement

#49 Composant wrapper
  src/App.tsx
  src/commons/constants.ts
  src/context/index.tsx
  src/main.tsx
  src/pages/Home.tsx
  src/pages/RootLayout.tsx
Labels: enhancement

#54 theme shadcn-ui orange
  src/App.css
Labels: enhancement

#52 Composant navbar
  public/logo.svg
  src/commons/constants.ts
  src/components/mode-toggle.tsx
  src/components/navbar/index.tsx
  src/components/navbar/toggle.tsx
  src/components/ui/navlink.tsx
  src/pages/Home.tsx
  src/pages/RootLayout.tsx
  src/types/app.ts
Labels: enhancement

#40 add connexion form with react-hook-form @hookform/resolvers zod
  package.json
  pnpm-lock.yaml
  src/commons/constants.ts
  src/components/form/auth-form.tsx
  src/components/navbar/toggle.tsx
  src/pages/Authentification.tsx
  src/types/app.ts
Labels: enhancement

#58 ajout d une page d erreur
  public/error-404.jpeg
  src/App.tsx
  src/pages/Error404.tsx
Labels: enhancement

#59 style: 💄Ajustement de style pour la page soit centrer
  src/pages/Error404.tsx
Labels: bug, enhancement

#68 Creation d une page profil
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/commons/constants.ts
  src/components/form/profile-form.tsx
  src/components/ui/link.tsx
  src/components/ui/separator.tsx
  src/pages/Profil.tsx
  src/pages/index.ts
  src/pages/profile/Favorite.tsx
  src/pages/profile/Profile.tsx
  src/pages/profile/SidebarNav.tsx
  src/pages/profile/index.tsx
  src/types/app.ts
Labels: enhancement

#71 fix: 🐛 change l'agencement du footer
  src/components/footer.tsx
Labels: bug

#73 Creation page accueil v2
  public/app_screen_1.svg
  public/app_screen_2.svg
  public/app_screen_3.svg
  src/App.tsx
  src/pages/Home.tsx
  src/pages/home/HomeItemSection.tsx
  src/pages/home/HomeSection.tsx
  src/pages/home/index.tsx
  src/pages/index.ts
Labels: bug, enhancement

#74 fix: 🐛 image 404 en svg pour la qualité et maintenance
  public/error-404.jpeg
  public/error_404.svg
  src/pages/Error404.tsx
Labels: bug

#75 fix: 🐛 correction de la largeur du formulaire
  src/pages/Authentification.tsx
Labels: bug

#77 refactor: 🎨utilisation de variables simple et
  src/commons/constants.ts
  src/components/footer.tsx
  src/components/navbar/index.tsx
  src/components/navbar/toggle.tsx
  src/components/ui/link.tsx
  src/components/ui/navlink.tsx
  src/helpers/index.ts
  src/pages/Authentification.tsx
  src/pages/profile/SidebarNav.tsx
  src/pages/profile/index.tsx
  src/types/app.ts
Labels: enhancement

#78 fix: 🐛 Correction de type
  src/components/form/auth-form.tsx
Labels: bug

#80 style: 💄ajustement du footer pour un meilleur visuel
  src/components/footer.tsx
Labels: enhancement

#83 Preparation supabase
  .env
  src/commons/constants.ts
  src/env.d.ts
  src/lib/supabase/client.ts
  src/lib/supabase/upload.ts
Labels: enhancement

#85 Creer un user supabase
  src/components/form/auth-form.tsx
  src/lib/supabase/auth.ts
Labels: enhancement

#89 feat: ✨/style: 💄ajout pour prendre en compte la
  src/components/ui/input.tsx
Labels: enhancement

#90 Mise en place de toast
  src/components/form/auth-form.tsx
  src/pages/RootLayout.tsx
Labels: enhancement

#91 fix: 🐛placement du toast après avoir signup
  src/components/form/auth-form.tsx
Labels: enhancement

#92 Refactoring page authentification
  src/components/form/auth-form.tsx
  src/pages/Authentification.tsx
  src/pages/authentification/AuthHeader.tsx
  src/pages/authentification/index.tsx
  src/pages/index.ts
Labels: enhancement

#99 bug: page error
  src/pages/Error404.tsx
Labels: bug

#102 typage database
  package.json
  pnpm-lock.yaml
  src/lib/supabase/client.ts
  src/types/supabase.ts
Labels: enhancement

#103 Hook creation user
  src/commons/api/clients/auth.ts
  src/commons/api/hooks/auth.ts
  src/components/form/auth-form.tsx
  src/components/toast-message.tsx
  src/lib/supabase/auth.ts
  src/types/supabase.ts
Labels: enhancement

#104 Creation fonction login + implémentation
  src/commons/api/clients/auth.ts
  src/commons/api/hooks/auth.ts
  src/components/form/auth-form.tsx
  src/helpers/index.ts
Labels: enhancement

#106 Composant login signup
  src/components/form/auth.tsx
  src/components/form/login.tsx
  src/components/form/profile.tsx
  src/components/form/signup.tsx
  src/pages/authentification/index.tsx
Labels: enhancement

#109 feat: ✨ajout de la fonction pour se déconnecter
  src/commons/api/clients/auth.ts
Labels: enhancement

#111 Creation hook auth
  src/commons/api/hooks/auth.ts
  src/components/form/auth.tsx
  src/components/form/login.tsx
  src/components/form/signup.tsx
Labels: enhancement

#112 Sprint 2
  .env
  package.json
  pnpm-lock.yaml
  public/app_screen_1.svg
  public/app_screen_2.svg
  public/app_screen_3.svg
  public/error-404.jpeg
  public/error_404.svg
  src/App.tsx
  src/commons/api/clients/auth.ts
  src/commons/api/hooks/auth.ts
  src/commons/constants.ts
  src/components/footer.tsx
  src/components/form/auth.tsx
  src/components/form/login.tsx
  src/components/form/profile.tsx
  src/components/form/signup.tsx
  src/components/navbar/index.tsx
  src/components/navbar/toggle.tsx
  src/components/toast-message.tsx
  src/components/ui/input.tsx
  src/components/ui/link.tsx
  src/components/ui/navlink.tsx
  src/components/ui/separator.tsx
  src/env.d.ts
  src/helpers/index.ts
  src/lib/supabase/client.ts
  src/lib/supabase/upload.ts
  src/pages/Authentification.tsx
  src/pages/Error404.tsx
  src/pages/Home.tsx
  src/pages/Profil.tsx
  src/pages/RootLayout.tsx
  src/pages/authentification/AuthHeader.tsx
  src/pages/authentification/index.tsx
  src/pages/home/HomeItemSection.tsx
  src/pages/home/HomeSection.tsx
  src/pages/home/index.tsx
  src/pages/index.ts
  src/pages/profile/Favorite.tsx
  src/pages/profile/Profile.tsx
  src/pages/profile/SidebarNav.tsx
  src/pages/profile/index.tsx
  src/types/app.ts
  src/types/supabase.ts
Labels: enhancement

#113 Auth context
  src/commons/api/clients/auth.ts
  src/commons/api/hooks/auth.ts
  src/context/AuthContext.tsx
  src/context/index.tsx
  src/hooks/useAuthContext.ts
Labels: enhancement

#114 Creation de route protegee
  src/App.tsx
  src/components/loading.tsx
  src/pages/RootLayout.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/config.tsx
Labels: enhancement

#121 fix: 🐛correction pour l'import de profile la sous page
  src/routes/config.tsx
Labels: bug

#124 Navbar gerer affichage
  public/default_avatar.svg
  src/components/navbar/index.tsx
  src/components/navbar/toggle.tsx
  src/components/navbar/toggle/index.tsx
  src/components/navbar/toggle/items.tsx
  src/components/navbar/user.tsx
Labels: enhancement

#128 fix: 🐛/refactor: 🎨 utilisation du bon import pour
  src/components/navbar/toggle/index.tsx
  src/components/navbar/toggle/items.tsx
  src/components/navbar/user.tsx
Labels: enhancement

#129 fix: 🐛correction de la condition
  src/components/footer.tsx
Labels: bug

#131 fix: 🐛 Correction de la récupération de auth
  src/context/AuthContext.tsx
Labels: bug

#133 Navbar: retour visuel
  src/components/navbar/index.tsx
  src/components/navbar/user.tsx
Labels: enhancement

#135 Bug: RootLayout
  src/pages/RootLayout.tsx
Labels: bug

#137 Fonction + hook recuperer profile + affichage les données
  src/commons/api/clients/profile.ts
  src/commons/api/hooks/profile.ts
  src/components/form/profile.tsx
  src/context/AuthContext.tsx
  src/types/database.ts
Labels: enhancement

#139 Function hook update profile & user
  src/commons/api/clients/auth.ts
  src/commons/api/clients/profile.ts
  src/commons/api/hooks/auth.ts
  src/commons/api/hooks/profile.ts
  src/components/form/profile.tsx
Labels: enhancement

#81 Création de page de recherche V2
  public/gallery-3.jpg
  src/commons/api/hooks/meal.ts
  src/commons/constants.ts
  src/components/form/search.tsx
  src/components/skeleton/HighLight.tsx
  src/components/skeleton/MealCard.tsx
  src/components/skeleton/MealCardList.tsx
  src/components/ui/input.tsx
  src/hooks/useSearch.ts
  src/pages/Search.tsx
  src/pages/Test.tsx
  src/pages/index.ts
  src/pages/search/HighLight.tsx
  src/pages/search/MealCard.tsx
  src/pages/search/MealCardList.tsx
  src/pages/search/index.tsx
  src/types/meal.ts
Labels: enhancement

#143 Bug: page profil
  src/commons/api/hooks/auth.ts
  src/commons/api/hooks/profile.ts
  src/components/form/profile.tsx
Labels: bug

#146 Page recette
  .env
  src/commons/api/hooks/meal.ts
  src/commons/constants.ts
  src/components/footer.tsx
  src/components/navbar/index.tsx
  src/env.d.ts
  src/pages/Produit.tsx
  src/pages/index.ts
  src/pages/recipe/index.tsx
  src/pages/recipe/ingredient/IngredientList.tsx
  src/pages/recipe/ingredient/index.tsx
  src/pages/recipe/instruction/InstructionList.tsx
  src/pages/recipe/instruction/index.tsx
  src/pages/search/MealCard.tsx
  src/routes/config.tsx
  src/types/meal.ts
Labels: enhancement

#148 MAJ dépendances
  package.json
  pnpm-lock.yaml
Labels: enhancement

#149 Sprint 3
  .env
  package.json
  pnpm-lock.yaml
  public/default_avatar.svg
  public/gallery-3.jpg
  src/App.tsx
  src/commons/api/clients/auth.ts
  src/commons/api/clients/profile.ts
  src/commons/api/hooks/auth.ts
  src/commons/api/hooks/meal.ts
  src/commons/api/hooks/profile.ts
  src/commons/constants.ts
  src/components/footer.tsx
  src/components/form/profile.tsx
  src/components/form/search.tsx
  src/components/loading.tsx
  src/components/navbar/index.tsx
  src/components/navbar/toggle.tsx
  src/components/navbar/toggle/index.tsx
  src/components/navbar/toggle/items.tsx
  src/components/navbar/user.tsx
  src/components/skeleton/HighLight.tsx
  src/components/skeleton/MealCard.tsx
  src/components/skeleton/MealCardList.tsx
  src/components/ui/input.tsx
  src/context/AuthContext.tsx
  src/context/index.tsx
  src/env.d.ts
  src/hooks/useAuthContext.ts
  src/hooks/useSearch.ts
  src/lib/client.ts
  src/pages/Produit.tsx
  src/pages/RootLayout.tsx
  src/pages/Search.tsx
  src/pages/Test.tsx
  src/pages/index.ts
  src/pages/recipe/index.tsx
  src/pages/recipe/ingredient/IngredientList.tsx
  src/pages/recipe/ingredient/index.tsx
  src/pages/recipe/instruction/InstructionList.tsx
  src/pages/recipe/instruction/index.tsx
  src/pages/search/HighLight.tsx
  src/pages/search/MealCard.tsx
  src/pages/search/MealCardList.tsx
  src/pages/search/index.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/config.tsx
  src/types/database.ts
  src/types/meal.ts
Labels: enhancement

#152 Avatar crud
  public/default_avatar.svg
  src/commons/api/clients/profile.ts
  src/commons/api/hooks/auth.ts
  src/commons/api/hooks/profile.ts
  src/components/form/profile.tsx
  src/components/navbar/user.tsx
  src/context/AuthContext.tsx
Labels: enhancement

#164 Test formulaire Auth
  package.json
  pnpm-lock.yaml
  src/commons/constants.ts
  src/components/form/auth.tsx
  src/components/form/profile.tsx
  src/pages/authentification/index.tsx
  src/setup.ts
  src/tests/integration/authenfication/index.test.tsx
  src/tests/setup.ts
  src/tests/unit/form/auth.test.tsx
  src/tests/utils.tsx
  tsconfig.json
  vite.config.ts
  vitest.config.ts
Labels: enhancement

#165 test: ✅ Ajout de test sur le hook useTheme
  src/tests/unit/hooks/useTheme.test.ts
Labels: enhancement

#166 Test: hook useSearch
  src/hooks/useSearch.ts
  src/tests/unit/hooks/useSearch.test.ts
Labels: enhancement

#168 test: ✅ Ajout de tests sur les fonctions API
  src/mocks/data/index.ts
  src/tests/unit/api/clients/auth.test.ts
Labels: enhancement

#171 fix: 🐛/ feat: ✨: déplacement de la logique + fix
  src/commons/api/hooks/auth.ts
  src/components/form/login.tsx
Labels: bug

#175 fix: 🐛 correction de l'affichage du theme et navlink
  src/components/navbar/toggle/items.tsx
Labels: bug

#174 Refonte_home_page
  public/app_screen_1.svg
  public/app_screen_2.svg
  public/app_screen_3.svg
  public/gallery-10.svg
  public/gallery-11.svg
  public/gallery-12.svg
  public/gallery-2.svg
  public/gallery-3.jpg
  public/gallery-3.svg
  public/gallery-4.svg
  public/gallery-5.svg
  public/gallery-8.svg
  public/gallery-9.svg
  src/pages/home/HomeItemSection.tsx
  src/pages/home/HomeSection.tsx
  src/pages/home/content/Eat.tsx
  src/pages/home/content/Recipes.tsx
  src/pages/home/content/index.tsx
  src/pages/home/header/HeaderSection.tsx
  src/pages/home/header/index.tsx
  src/pages/home/index.tsx
Labels: enhancement

#177 fix: 🐛 Changement d'extension d'image
  src/pages/search/index.tsx
Labels: bug

#178 feat: ✨Ajout en favoris depuis la page recette
  src/pages/recipe/index.tsx
Labels: enhancement

#180 fix: 🐛 changer la couleur pour le favoris en dark mode
  src/pages/recipe/index.tsx
Labels: bug

#181 feat: ✨Ajout des favoris dans la page profile
  src/commons/api/hooks/meal.ts
  src/pages/profile/Favorite.tsx
Labels: enhancement

#184 Tests fonctions profiles
  package.json
  pnpm-lock.yaml
  src/mocks/data/index.ts
  src/mocks/data/server.ts
  src/mocks/handlers.ts
  src/tests/setup.ts
  src/tests/unit/api/clients/profile.test.ts
Labels: enhancement

#186 fix: 🐛correction de du test upload image
  src/tests/unit/api/clients/profile.test.ts
Labels: bug

#188 refactor: 🎨 refonte url pour les tests
  src/mocks/handlers.ts
  src/tests/unit/api/clients/profile.test.ts
Labels: enhancement

#190 refactor: 🎨Dissocier l'appel d'API
  src/commons/api/clients/meal.ts
  src/commons/api/hooks/meal.ts
Labels: enhancement

#192 fix: 🐛correction de la visiblité du bouton favoris
  src/pages/recipe/index.tsx
Labels: bug

#194 style: 💄refactor: 🎨Refonte de la meal card
  src/components/skeleton/MealCard.tsx
  src/pages/profile/Favorite.tsx
  src/pages/profile/Profile.tsx
  src/pages/profile/index.tsx
  src/pages/search/MealCard.tsx
Labels: enhancement

#196 refactor: 🎨nettoayge de fichier non utilisé
  src/pages/Test.tsx
Labels: enhancement

#197 style: 💄/fix: 🐛 correction + composant de shadcn:
  src/pages/profile/Favorite.tsx
  src/pages/profile/Profile.tsx
  src/pages/profile/SidebarNav.tsx
  src/pages/profile/index.tsx
Labels: bug, enhancement

#200 feat: ✨Ajout d'un skeleton pour la page recette
  src/components/skeleton/recipe/Ingredient.tsx
  src/components/skeleton/recipe/IngredientList.tsx
  src/components/skeleton/recipe/Instruction.tsx
  src/components/skeleton/recipe/InstructionList.tsx
  src/components/skeleton/recipe/index.tsx
  src/pages/recipe/index.tsx
Labels: enhancement

#202 fix: 🐛Correction de skeleton + flexibilité des skeletons
  src/components/skeleton/HighLight.tsx
  src/components/skeleton/MealCard.tsx
  src/components/skeleton/MealCardList.tsx
Labels: bug

#204 fix: 🐛Correction du chevauchements des recettes
  src/pages/profile/index.tsx
Labels: bug

#206 refactor: 🎨uniformisation des urls
  src/commons/api/clients/meal.ts
  src/commons/constants.ts
  src/mocks/handlers.ts
  src/tests/unit/api/clients/profile.test.ts
Labels: enhancement

#207 refactor: 🎨renommage
  src/commons/api/clients/meal.ts
  src/commons/constants.ts
Labels: enhancement

#209 Test fonction api
  src/mocks/data/index.ts
  src/mocks/handlers.ts
  src/tests/unit/api/clients/auth.test.ts
  src/tests/unit/api/clients/meal.test.ts
  src/tests/unit/api/clients/profile.test.ts
  src/types/meal.ts
Labels: enhancement
